### ISSUE TITLE
разобраться, почему не работает тест

### ISSUE THREAD

**Issue by baranov1ch** [cscenter/node-sdch-proxy#11]
expected undefined to include 'sdch'

**Comment by baranov1ch** [comment]
есть подозрение, что это из-за сликом маленького размера ответа. там по минимуму должен быть 1Кб. Надо или передать что-то такое, или поменять threshold у connect-sdch:
https://github.com/baranov1ch/connect-sdch/blob/master/test/connect-sdch.coffee#L273

**Comment by rurenko** [comment]
Действительно, я исправил тест, теперь все ОК.
