### ISSUE TITLE
Too long path

### ISSUE THREAD

**Issue by rurenko** [cscenter/node-sdch-proxy#15]
Иногда попрадаются очень длинные url:
http://ru.wikipedia.org/wiki/%D0%AD%D0%BD%D1%86%D0%B8%D0%BA%D0%BB%D0%BE%D0%BF%D0%B5%D0%B4%D0%B8%D1%87%D0%B5%D1%81%D0%BA%D0%B8%D0%B9_%D1%81%D0%BB%D0%BE%D0%B2%D0%B0%D1%80%D1%8C_%D0%91%D1%80%D0%BE%D0%BA%D0%B3%D0%B0%D1%83%D0%B7%D0%B0_%D0%B8_%D0%95%D1%84%D1%80%D0%BE%D0%BD%D0%B0
которые после преобразования становятся еще длиннее. В результате при попытке fs.createWriteStream( .. ) ловим ошибку:
Stream page: { [Error: ENAMETOOLONG, open './pages/wikipedia.org/%2Fwiki%2F%25D0%25AD%25D0%25BD%25D1%2586%25D0%25B8%25D0%25BA%25D0%25BB%25D0%25BE%25D0%25BF%25D0%25B5%25D0%25B4%25D0%25B8%25D1%2587%25D0%25B5%25D1%2581%25D0%25BA%25D0%25B8%25D0%25B9_%25D1%2581%25D0%25BB%25D0%25BE%25D0%25B2%25D0%25B0%25D1%2580%25D1%258C_%25D0%2591%25D1%2580%25D0%25BE%25D0%25BA%25D0%25B3%25D0%25B0%25D1%2583%25D0%25B7%25D0%25B0_%25D0%25B8_%25D0%2595%25D1%2584%25D1%2580%25D0%25BE%25D0%25BD%25D0%25B0']
  errno: 49,
  code: 'ENAMETOOLONG',
  path: './pages/wikipedia.org/%2Fwiki%2F%25D0%25AD%25D0%25BD%25D1%2586%25D0%25B8%25D0%25BA%25D0%25BB%25D0%25BE%25D0%25BF%25D0%25B5%25D0%25B4%25D0%25B8%25D1%2587%25D0%25B5%25D1%2581%25D0%25BA%25D0%25B8%25D0%25B9_%25D1%2581%25D0%25BB%25D0%25BE%25D0%25B2%25D0%25B0%25D1%2580%25D1%258C_%25D0%2591%25D1%2580%25D0%25BE%25D0%25BA%25D0%25B3%25D0%25B0%25D1%2583%25D0%25B7%25D0%25B0_%25D0%25B8_%25D0%2595%25D1%2584%25D1%2580%25D0%25BE%25D0%25BD%25D0%25B0' }

**Comment by baranov1ch** [comment]
давай в качестве имени файла использовать тогда не путь, а sha256 от пути.

**Comment by rurenko** [comment]
В качестве имени использовал sha256.

**Comment by baranov1ch** [comment]
лучше скачивать страницу целиком, считать md5 от нее и сохранять с таким именем

**Comment by baranov1ch** [comment]
#16
