### ISSUE TITLE
сделать возможность стримить тела страниц в файл вместе с отдачей клиенту.

### ISSUE THREAD

**Issue by baranov1ch** [cscenter/node-sdch-proxy#5]
надо в конфиге добавить возможность задавать список доменов, для которых страницы будут складываться в указанную по пути:
`rootdir/$(domain name)/$(path)`

`rootdir` будет задаваться тоже конфигом.

`$(domain name)` - имя домена

`$(path)` - путь. Видимо, слеши в урлах (и прочую нечисть) надо будет заэскейпить с помощью url esacping'а (гугл в помощь)

**Comment by rurenko** [comment]
реализовано

**Comment by baranov1ch** [comment]
https://github.com/cscenter/node-sdch-proxy/pull/12
